### ISSUE TITLE
Enable WIFI support

### ISSUE THREAD

**Issue by liminal-loop** [bottomquark/esp8266_reed_contact#1]
Implement possibility to 
* configure a WIFI network
* connect to a WIFI network
* reconnect if connection lost

**Comment by liminal-loop** [comment]
@bottomquark : don't understand why the build in led not blinking during connection establishment.

**Comment by bottomquark** [comment]
It does not blink because the pin is effectively always HIGH. In line 28 of wifi.cpp you pull the LED pin HIGH, in line 34 you pull it LOW. The code jumps immediately from line 34 to line 28, therefore the LED does not blink.

Adding a  delay(200); after line 34 should fix that.

Just for your information: the LED is on when the pin is LOW and off if the pin is HIGH

**Comment by liminal-loop** [comment]
oh. thanks. blinking is fixed :)

**Comment by georg-koch** [comment]
#1
